# Font Style		Values
font_family		Maple Mono Italic
font_size		11

# Cursor Shape
shell_integration	no-cursor
cursor_shape		beam

# Window Style
window_padding_width	5

# Background
background_opacity	0.5
background_blur		1

# Functionality
confirm_os_window_close 0

# Colors
cursor			#701cf5

background		#100c1c
foreground		#c0d2f6

selection_background	#c0d2f6
selection_foreground	#141430

color0               #000000
color8               #9291d6
color1               #e92d6d
color9               #e92d6d
color2               #36cb89
color10              #36cb89
color3               #e7dd53
color11              #e7dd53
color4               #47ade7
color12              #47ade7
color5               #d775e2
color13              #d775e2
color6               #701cf5
color14              #701cf5
color7               #bdcef1
color15              #9291d6
