# Font Style		Values
font_family		Maple Mono Italic
font_size		11

# Cursor Shape
shell_integration	no-cursor
cursor_shape		beam

# Window Style
window_padding_width	5

# Background
background_opacity	0.4
background_blur		1

# Functionality
confirm_os_window_close 0

# Colors
cursor			#196052

background		#0e0f13
foreground		#f0eade

selection_background	#f0eade
selection_foreground	#0e0f13

color0               #f2d2bf
color8               #ffd37d
color1               #db2835
color9               #db2835
color2               #37cc65
color10              #37cc65
color3               #ffd600
color11              #ffd600
color4               #43ccd2
color12              #43ccd2
color5               #e21497
color13              #e21497
color6               #a634b4
color14              #a634b4
color7               #458766
color15              #8b373d
