# Font Style		Values
font_family		Maple Mono Italic
font_size		11

# Cursor Shape
shell_integration	no-cursor
cursor_shape		beam

# Window Style
window_padding_width	5

# Background
background_opacity	0.38
background_blur		1

# Functionality
confirm_os_window_close 0

# Colors
cursor			#c75583

background		#000000
foreground		#f8e0ee

selection_background	#f8e0ee
selection_foreground	#000000

color0               #732863
color8               #cf81e3
color1               #e74362
color9               #e74362
color2               #5ddc7e
color10              #5ddc7e
color3               #f3dc64
color11              #f3dc64
color4               #55b6c7
color12              #55b6c7
color5               #ea6198
color13              #ea6198
color6               #b257e3
color14              #b257e3
color7               #fe83df
color15              #f8e0ee
