# General configuration
general {
    monitor =
    halign = center
    valign = center
}

# Lock screen background
background {
    path = ~/Pictures/Wallpapers/waifu_pink.png
    blur_passes = 2
    noise = 0.051
}

# Current time
label {
    text = cmd[update:1000] echo -e "$(date +"%H:%M")"
    font_family = Galafera
    font_size = 100
    color = rgb(233, 216, 223)
    position = 0, 330
}

# Current date/month
label {
    text = cmd[update:1000] echo -e "• $(date +"%A, %B %d") •"
    font_family = Crocodile Script
    font_size = 39
    color = rgb(233, 216, 223)
    position = 0, 243
}

# Sleeping cat
label {
    text = k
    font_family = Meows Nepil Illustration
    font_size = 45
    color = rgb(233, 216, 223)
    position = -80, -96
}

# Profile picture
image {
    path = ~/Pictures/Icons/pink.jpg
    size = 160
    border-color = rgb(233, 216, 223)
    border-size = 2
    position = 0, 45
    reload_time = -1
    reload_cmd =
}

# User field
shape {
    color = rgba(255, 255, 255, .1)
    size = 290, 60
    rounding = -1
    position = 0, -140
    xray = false
}

label {
    text =   $USER      
    font_family = Maple Mono Italic
    font_size = 18
    color = rgba(255, 233, 242, 0.8)
    position = 0, -140
}

# Password field
input-field {
    placeholder_text = <i><span foreground="##ffffff99">   Password</span></i>
    font_family = Maple Mono Italic
    font_color = rgb(233, 216, 223)
    inner_color = rgba(255, 255, 255, 0.1)
    outer_color = rgba(255, 255, 255, 0)
    outline_thickness = 2
    size = 290, 60
    dots_size = 0.2
    dots_spacing = 0.2
    position = 0, -210
    dots_center = true
    fade_on_empty = false
    hide_input = false
}

# Suspend button
label {
    text =  󰤄 
    font_size = 50
    color = rgb(233, 216, 223)
    position = 820, 140
    halign = left
    valign = bottom
    onclick = systemctl suspend
}

# Power-off button
label {
    text =  󰐥 
    font_size = 50
    color = rgb(233, 216, 223)
    position = 0, 140
    halign = center
    valign = bottom
    onclick = shutdown now
}

# Reboot button
label {
    text =  󰜉 
    font_size = 50
    color = rgb(233, 216, 223)
    position = -820, 140
    halign = right
    valign = bottom
    onclick = reboot now
}