# General configuration
general {
    lock_cmd = pidof hyprlock || hyprlock      # Avoid multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session   # Lock screen before sleep
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Set monitor backlight to minimum
listener {
    timeout = 180 # 3min
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# Turn off keyboard backlight
listener {
    timeout = 300 # 5min
    on-timeout = brightnessctl -sd samsung-galaxybook::kbd_backlight set 0
    on-resume = brightnessctl -rd samsung-galaxybook::kbd_backlight
}

# Lock screen
listener {
    timeout = 300 # 5min
    on-timeout = loginctl lock-session
}

# Turn off screen
listener {
    timeout = 600 # 10min
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

# Suspend computer
listener {
    timeout = 1800 # 30min
    on-timeout = systemctl suspend
}
