# General configuration
general {
    monitor =
    halign = center
    valign = center
}

# Lock screen background
background {
    path = ~/Pictures/Wallpapers/lain-faces.png
    blur_passes = 3
    noise = 0.051
}

# Current time
label {
    text = cmd[update:1000] echo -e "$(date +"%H:%M")"
    font_family = Galafera
    font_size = 100
    color = rgb(240, 234, 222)
    position = 0, 330
}

# Current date/month
label {
    text = cmd[update:1000] echo -e "• $(date +"%A, %B %d") •"
    font_family = Love Letter Typewriter
    font_size = 24
    color = rgb(240, 234, 222)
    position = 0, 243
}

# No matter where you are, everyone is always connected!
label {
    text = どこにいたって、人は繋がっているのよ
    font_family = Love Letter Typewriter
    font_size = 12
    color = rgb(154, 154, 170)
    position = 0, 200
}

# Profile picture
image {
    path = ~/Pictures/Icons/lainwires.png
    border_size = 3
    border_color = rgba(240, 234, 222, 0.3)
    size = 200
    rounding = -1
    reload_time = -1
    reload_cmd = 
    position = 0, 20
}

# User field
shape {
    color = rgba(255, 255, 255, 0.1)
    size = 290, 60
    rounding = -1
    position = 0, -160
    xray = false
}

label {
    text =   $USER      
    font_family = Maple Mono Italic
    font_size = 18
    color = rgb(240, 234, 222)
    position = 0, -160
}

# Password field
input-field {
    placeholder_text = <i><span foreground="##ffffff99">   Password</span></i>
    font_family = Maple Mono Italic
    font_color = rgb(240, 234, 222)
    inner_color = rgba(255, 255, 255, 0.1)
    outer_color = rgba(255, 255, 255, 0)
    outline_thickness = 2
    size = 290, 60
    dots_size = 0.2
    dots_spacing = 0.2
    position = 0, -230
    dots_center = true
    fade_on_empty = false
    hide_input = false
}

# Suspend button
label {
    text =  󰤄 
    font_size = 50
    color = rgb(240, 234, 222)
    position = 820, 140
    halign = left
    valign = bottom
    onclick = systemctl suspend
}

# Power-off button
label {
    text =  󰐥 
    font_size = 50
    color = rgb(240, 234, 222)
    position = 0, 140
    halign = center
    valign = bottom
    onclick = shutdown now
}

# Reboot button
label {
    text =  󰜉 
    font_size = 50
    color = rgb(240, 234, 222)
    position = -820, 140
    halign = right
    valign = bottom
    onclick = reboot now
}
