mainFont=./Resources/Fonts/MapleMono-TTF.zip
wallpaper=./Resources/Images/Wallpapers/lainwired.jpg
hyprRice=./$riceRoot/dotfiles/hypr
waybRice=./$riceRoot/dotfiles/waybar
kittyRice=./$riceRoot/dotfiles/kitty/kitty.conf
fetchRice=./$riceRoot/dotfiles/fastfetch/config.jsonc
fetchLogo=./Resources/Images/Fastfetch/lain.png
rofiRice=./$riceRoot/dotfiles/rofi/config.rasi
codeRice=./$riceRoot/vscode/settings.json
discRice=./$riceRoot/discord/theme.css
soundsDir=./Resources/Sounds
