mainFont=./Resources/Fonts/MapleMono-TTF.zip
wallpaper=./Resources/Images/Wallpapers/waifu_pink.png
customIcons=./Resources/Icons/Reversal-pink.tar.xz
soundEffectsDir=./Resources/Sounds
hyprRice=./$riceRoot/dotfiles/hypr
waybarRice=./$riceRoot/dotfiles/waybar
kittyRice=./$riceRoot/dotfiles/kitty/kitty.conf
fastfetchRice=./$riceRoot/dotfiles/fastfetch/config.jsonc
fastfetchLogo=./Resources/Images/Fastfetch/nyarch-pink.png
rofiRice=./$riceRoot/dotfiles/rofi/config.rasi
wlogoutRice=./$riceRoot/dotfiles/wlogout
vscodeRice=./$riceRoot/vscode/settings.json
discordRice=./$riceRoot/discord/theme.css
